import{a as L,S as P,i}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const b="50629766-ca4e4f15305d377d5e3228fef",S="https://pixabay.com/api/";async function y(s,r=1,t=15){const a={key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t};try{return(await L.get(S,{params:a})).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),q=new P(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const r=s.map(t=>`
        <li class="gallery-item">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}" class="image"/>
            </a>
            <div class="description">
                <p class="text">Likes <span class="span">${t.likes}</span></p>
                <p class="text">Views <span class="span">${t.views}</span></p>
                <p class="text">Comments <span class="span">${t.comments}</span></p>
                <p class="text">Downloads <span class="span">${t.downloads}</span></p>
            </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",r),q.refresh()}function v(){f.innerHTML=""}function m(){g.style.display="block"}function w(){g.style.display="none"}const x=document.querySelector(".form");document.querySelector(".gallery");const d=document.querySelector(".load-button");let n=1,c=15,u="";function p(){d.classList.add("hidden")}function R(){d.classList.remove("hidden")}x.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(!r){i.warning({title:"warning",message:"Please enter a search term",position:"topRight"});return}u=r,n=1,v(),m(),p();try{const t=await y(u,n,c),{hits:a}=t;a.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(h(a),R());const e=Math.ceil(t.totalHits/c);n>=e&&p()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});d.addEventListener("click",async()=>{n+=1,m();try{const s=await y(u,n,c);h(s.hits);const r=Math.ceil(s.totalHits/c);n>=r&&(p(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
