import{a as L,S as b,i}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const P="50629766-ca4e4f15305d377d5e3228fef",S="https://pixabay.com/api/";async function y(o,r=1,t=15){const a={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t};try{return(await L.get(S,{params:a})).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const r=o.map(t=>`
        <li class="gallery-item">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}" class="image"/>
            </a>
            <div class="description">
                <p class="text">Likes <span class="span">${t.likes}</span></p>
                <p class="text">Views <span class="span">${t.views}</span></p>
                <p class="text">Comments <span class="span">${t.comments}</span></p>
                <p class="text">Downloads <span class="span">${t.downloads}</span></p>
            </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",r),q.refresh()}function v(){f.innerHTML=""}function m(){g.style.display="block"}function w(){g.style.display="none"}const x=document.querySelector(".form");document.querySelector(".gallery");const p=document.querySelector(".load-button");let n=1,c=15,d="";function l(){p.classList.add("hidden")}function R(){p.classList.remove("hidden")}x.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){i.warning({title:"warning",message:"Please enter a search term",position:"topRight"});return}d=r,n=1,v(),m(),l();try{const t=await y(d,n,c),{hits:a}=t;a.length===0?(i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l()):(h(a),R());const e=Math.ceil(t.totalHits/c);n>=e&&l()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});p.addEventListener("click",async()=>{n+=1,m();try{const o=await y(d,n,c);h(o.hits);const r=document.querySelector(".gallery-item");if(r){const a=r.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const t=Math.ceil(o.totalHits/c);n>=t&&(l(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
